services:
  app:
    build: .
    volumes:
      - ./data/db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    environment:
      DEBUG_MODE: 'True'
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app