services:
  app:
    build: .
    volumes:
      - ./data/db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    environment:
      DEBUG_MODE: 'True'
#      CSRF_TRUSTED_ORIGINS: 'http://your.domain.com,https://your.domain.com'
  nginx:
    image: nginx
    ports:
      - "8080:80"
#      - "port:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app
#      - /path/to/your/cert:/etc/ssl/fullchain.pem
#      - /path/to/your/privkey:/etc/ssl/privkey.pem