# Generated by Django 5.1.2 on 2024-10-10 16:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'create_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepaymentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('principal_paid', models.DecimalField(decimal_places=4, max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebtRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('principal', models.DecimalField(decimal_places=4, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=4, max_digits=12)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_lender', models.BooleanField(default=False)),
                ('is_borrower', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'create_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='loan_app_us_name_a06dd3_idx')],
            },
        ),
        migrations.AddField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='loan_app.user'),
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='loan_app.user')),
            ],
            options={
                'ordering': ['name', 'create_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='loan_app_le_name_e89211_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['name'], name='loan_app_bo_name_b55651_idx'),
        ),
    ]
