# Generated by Django 5.1.2 on 2024-10-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtrecords',
            name='lender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loan_app.lender'),
        ),
    ]
