# Generated by Django 5.1.2 on 2024-10-11 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_debtrecords_lender'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='avatar',
            field=models.CharField(default='https://www.flaticon.com/free-icons/portrait', max_length=255),
        ),
        migrations.AddField(
            model_name='lender',
            name='avatar',
            field=models.CharField(default='https://www.flaticon.com/free-icons/portrait', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://www.flaticon.com/free-icons/portrait', max_length=255),
        ),
        migrations.AlterField(
            model_name='debtrecords',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.lender'),
        ),
    ]
