# Generated by Django 5.1.2 on 2024-10-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_borrower_avatar_lender_avatar_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='avatar',
            field=models.CharField(default='https://litchi-beer.oss-cn-shanghai.aliyuncs.com/avatar.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='lender',
            name='avatar',
            field=models.CharField(default='https://litchi-beer.oss-cn-shanghai.aliyuncs.com/avatar.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://litchi-beer.oss-cn-shanghai.aliyuncs.com/avatar.jpg', max_length=255),
        ),
    ]
