# Generated by Django 5.1.2 on 2024-10-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_alter_borrower_avatar_alter_lender_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtrecords',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='loan_app.borrower'),
        ),
        migrations.AlterField(
            model_name='debtrecords',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='loan_app.lender'),
        ),
    ]
