# Generated by Django 5.1.2 on 2024-10-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0005_alter_debtrecords_borrower_alter_debtrecords_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtrecords',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_borrower', to='loan_app.borrower'),
        ),
        migrations.AlterField(
            model_name='debtrecords',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_lender', to='loan_app.lender'),
        ),
    ]
