# Generated by Django 5.1.2 on 2024-10-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_alter_debtrecords_borrower_alter_debtrecords_lender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtrecords',
            name='interest',
        ),
        migrations.AlterField(
            model_name='debtrecords',
            name='interest_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='debtrecords',
            name='principal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
